import type { IncidentFamily, IncidentProfile } from "./incident-profile";
export interface IncidentTopic {
  id: string;
  name: string;
  section: number;
  family: IncidentFamily;
  site: IncidentProfile["site"];
  size: number;
  tags: string[];
}
/** Audited against request sections 3-10. Repeated subjects retain a source row but share generated IDs. */
export const incidentTopics: IncidentTopic[] = [
  {
    id: "muelleimerbrand",
    name: "Mülleimerbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: [],
  },
  {
    id: "muellcontainerbrand",
    name: "Müllcontainerbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: ["container"],
  },
  {
    id: "papiercontainerbrand",
    name: "Papiercontainerbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: ["paper", "container"],
  },
  {
    id: "altkleidercontainerbrand",
    name: "Altkleidercontainerbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: ["textile", "container"],
  },
  {
    id: "pkw-brand",
    name: "Pkw-Brand",
    section: 3,
    family: "vehicle-fire",
    site: "street",
    size: 2,
    tags: ["fuel"],
  },
  {
    id: "lkw-brand",
    name: "Lkw-Brand",
    section: 3,
    family: "vehicle-fire",
    site: "street",
    size: 3,
    tags: ["fuel"],
  },
  {
    id: "busbrand",
    name: "Busbrand",
    section: 3,
    family: "vehicle-fire",
    site: "street",
    size: 3,
    tags: ["fuel"],
  },
  {
    id: "motorradbrand",
    name: "Motorradbrand",
    section: 3,
    family: "vehicle-fire",
    site: "street",
    size: 1,
    tags: ["fuel"],
  },
  {
    id: "fahrrad-akku-brand",
    name: "Fahrrad-/Akku-Brand",
    section: 3,
    family: "vehicle-fire",
    site: "street",
    size: 1,
    tags: ["battery"],
  },
  {
    id: "garagenbrand",
    name: "Garagenbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "carportbrand",
    name: "Carportbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: ["wood"],
  },
  {
    id: "gartenlaubenbrand",
    name: "Gartenlaubenbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: ["wood"],
  },
  {
    id: "schuppenbrand",
    name: "Schuppenbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: ["wood"],
  },
  {
    id: "heckenbrand",
    name: "Heckenbrand",
    section: 3,
    family: "vegetation",
    site: "field",
    size: 1,
    tags: ["vegetation"],
  },
  {
    id: "grasflaechenbrand",
    name: "Grasflächenbrand",
    section: 3,
    family: "vegetation",
    site: "field",
    size: 1,
    tags: ["vegetation"],
  },
  {
    id: "boeschungsbrand",
    name: "Böschungsbrand",
    section: 3,
    family: "vegetation",
    site: "field",
    size: 2,
    tags: ["vegetation"],
  },
  {
    id: "feldbrand",
    name: "Feldbrand",
    section: 3,
    family: "vegetation",
    site: "field",
    size: 3,
    tags: ["vegetation"],
  },
  {
    id: "strohballenbrand",
    name: "Strohballenbrand",
    section: 3,
    family: "vegetation",
    site: "field",
    size: 2,
    tags: ["straw"],
  },
  {
    id: "waldbrand",
    name: "Waldbrand",
    section: 3,
    family: "vegetation",
    site: "forest",
    size: 3,
    tags: ["vegetation"],
  },
  {
    id: "kuechenbrand",
    name: "Küchenbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: ["oil"],
  },
  {
    id: "wohnzimmerbrand",
    name: "Wohnzimmerbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "schlafzimmerbrand",
    name: "Schlafzimmerbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "kellerbrand",
    name: "Kellerbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: [],
  },
  {
    id: "fassadenbrand",
    name: "Fassadenbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: ["insulation"],
  },
  {
    id: "balkonbrand",
    name: "Balkonbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "wohnungsbrand",
    name: "Wohnungsbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: [],
  },
  {
    id: "mehrfamilienhausbrand",
    name: "Mehrfamilienhausbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 3,
    tags: ["height"],
  },
  {
    id: "dachstuhlbrand",
    name: "Dachstuhlbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: ["insulation", "height"],
  },
  {
    id: "treppenhausbrand",
    name: "Treppenhausbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: ["height"],
  },
  {
    id: "hochhausbrand",
    name: "Hochhausbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 3,
    tags: ["height"],
  },
  {
    id: "hallenbrand",
    name: "Hallenbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 3,
    tags: [],
  },
  {
    id: "lagerhallenbrand",
    name: "Lagerhallenbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 3,
    tags: [],
  },
  {
    id: "werkstattbrand",
    name: "Werkstattbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 2,
    tags: [],
  },
  {
    id: "industriebrand",
    name: "Industriebrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 3,
    tags: ["chemical"],
  },
  {
    id: "maschinenbrand",
    name: "Maschinenbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 2,
    tags: ["oil"],
  },
  {
    id: "foerderbandbrand",
    name: "Förderbandbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 2,
    tags: ["oil"],
  },
  {
    id: "tankstellenbrand",
    name: "Tankstellenbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 3,
    tags: ["fuel"],
  },
  {
    id: "reifenlagerbrand",
    name: "Reifenlagerbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 3,
    tags: ["rubber"],
  },
  {
    id: "baustellenbrand",
    name: "Baustellenbrand",
    section: 3,
    family: "structure-fire",
    site: "construction",
    size: 2,
    tags: [],
  },
  {
    id: "containerbrand",
    name: "Containerbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: ["container"],
  },
  {
    id: "supermarktbrand",
    name: "Supermarktbrand",
    section: 3,
    family: "structure-fire",
    site: "commercial",
    size: 2,
    tags: [],
  },
  {
    id: "einkaufszentrumbrand",
    name: "Einkaufszentrumbrand",
    section: 3,
    family: "structure-fire",
    site: "commercial",
    size: 3,
    tags: ["public"],
  },
  {
    id: "schulbrand",
    name: "Schulbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: ["children"],
  },
  {
    id: "kindergartenbrand",
    name: "Kindergartenbrand",
    section: 3,
    family: "structure-fire",
    site: "public",
    size: 2,
    tags: ["wood", "children"],
  },
  {
    id: "hotelbrand",
    name: "Hotelbrand",
    section: 3,
    family: "structure-fire",
    site: "public",
    size: 3,
    tags: ["public"],
  },
  {
    id: "restaurantbrand",
    name: "Restaurantbrand",
    section: 3,
    family: "structure-fire",
    site: "public",
    size: 2,
    tags: ["public"],
  },
  {
    id: "discotheken-clubbrand",
    name: "Discotheken-/Clubbrand",
    section: 3,
    family: "structure-fire",
    site: "public",
    size: 2,
    tags: ["public"],
  },
  {
    id: "bahnhofsbrand",
    name: "Bahnhofsbrand",
    section: 3,
    family: "structure-fire",
    site: "public",
    size: 2,
    tags: ["public"],
  },
  {
    id: "parkhausbrand",
    name: "Parkhausbrand",
    section: 3,
    family: "structure-fire",
    site: "commercial",
    size: 2,
    tags: [],
  },
  {
    id: "tunnelbrand",
    name: "Tunnelbrand",
    section: 3,
    family: "industry-fire",
    site: "industrial",
    size: 3,
    tags: ["tunnel"],
  },
  {
    id: "zugbrand",
    name: "Zugbrand",
    section: 3,
    family: "industry-fire",
    site: "rail",
    size: 3,
    tags: ["rail"],
  },
  {
    id: "strassenbahnbrand",
    name: "Straßenbahnbrand",
    section: 3,
    family: "industry-fire",
    site: "rail",
    size: 2,
    tags: ["rail"],
  },
  {
    id: "trafo-technikbrand",
    name: "Trafo-/Technikbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: ["electrical"],
  },
  {
    id: "kabelbrand",
    name: "Kabelbrand",
    section: 3,
    family: "small-fire",
    site: "street",
    size: 1,
    tags: ["electrical"],
  },
  {
    id: "daemmstoff-isolierungsbrand",
    name: "Dämmstoff-/Isolierungsbrand",
    section: 3,
    family: "structure-fire",
    site: "residential",
    size: 2,
    tags: ["insulation"],
  },
  {
    id: "baum-auf-strasse",
    name: "Baum auf Straße",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["storm"],
  },
  {
    id: "baum-auf-gebaeude",
    name: "Baum auf Gebäude",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["storm"],
  },
  {
    id: "baum-auf-fahrzeug",
    name: "Baum auf Fahrzeug",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["storm"],
  },
  {
    id: "ast-droht-zu-fallen",
    name: "Ast droht zu fallen",
    section: 4,
    family: "technical",
    site: "street",
    size: 1,
    tags: ["storm"],
  },
  {
    id: "dachschaden",
    name: "Dachschaden",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["height"],
  },
  {
    id: "dachziegel-drohen-zu-fallen",
    name: "Dachziegel drohen zu fallen",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["height"],
  },
  {
    id: "baukran-beschaedigt",
    name: "Baukran beschädigt",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["height"],
  },
  {
    id: "baukran-droht-umzustuerzen",
    name: "Baukran droht umzustürzen",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["height"],
  },
  {
    id: "geruest-eingestuerzt",
    name: "Gerüst eingestürzt",
    section: 4,
    family: "collapse",
    site: "residential",
    size: 2,
    tags: ["collapse", "height"],
  },
  {
    id: "person-auf-geruest",
    name: "Person auf Gerüst",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["height", "injury"],
  },
  {
    id: "person-auf-dach",
    name: "Person auf Dach",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["height", "injury"],
  },
  {
    id: "person-in-schacht",
    name: "Person in Schacht",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["injury"],
  },
  {
    id: "person-in-grube",
    name: "Person in Grube",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["injury"],
  },
  {
    id: "verschuettete-person",
    name: "verschüttete Person",
    section: 4,
    family: "collapse",
    site: "street",
    size: 3,
    tags: ["collapse", "trapped", "injury"],
  },
  {
    id: "gebaeudeeinsturz",
    name: "Gebäudeeinsturz",
    section: 4,
    family: "collapse",
    site: "residential",
    size: 3,
    tags: ["collapse"],
  },
  {
    id: "gebaeudeteileinsturz",
    name: "Gebäudeteileinsturz",
    section: 4,
    family: "collapse",
    site: "residential",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "decke-eingestuerzt",
    name: "Decke eingestürzt",
    section: 4,
    family: "collapse",
    site: "residential",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "wand-eingestuerzt",
    name: "Wand eingestürzt",
    section: 4,
    family: "collapse",
    site: "residential",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "fahrzeug-unter-gebaeudeteil",
    name: "Fahrzeug unter Gebäudeteil",
    section: 4,
    family: "collapse",
    site: "residential",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "baustellenunfall",
    name: "Baustellenunfall",
    section: 4,
    family: "technical",
    site: "construction",
    size: 1,
    tags: ["trapped", "injury"],
  },
  {
    id: "maschinenunfall",
    name: "Maschinenunfall",
    section: 4,
    family: "technical",
    site: "industrial",
    size: 1,
    tags: ["trapped", "injury"],
  },
  {
    id: "arbeitsunfall",
    name: "Arbeitsunfall",
    section: 4,
    family: "technical",
    site: "industrial",
    size: 1,
    tags: ["trapped", "injury"],
  },
  {
    id: "person-eingeklemmt",
    name: "Person eingeklemmt",
    section: 4,
    family: "technical",
    site: "street",
    size: 1,
    tags: ["trapped", "injury"],
  },
  {
    id: "person-unter-fahrzeug",
    name: "Person unter Fahrzeug",
    section: 4,
    family: "technical",
    site: "street",
    size: 1,
    tags: ["trapped", "injury"],
  },
  {
    id: "aufzug",
    name: "Aufzug",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["lift"],
  },
  {
    id: "tueroeffnung-medizinischer-notfall",
    name: "Türöffnung medizinischer Notfall",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["medical"],
  },
  {
    id: "tueroeffnung-polizei",
    name: "Türöffnung Polizei",
    section: 4,
    family: "technical",
    site: "residential",
    size: 1,
    tags: ["security"],
  },
  {
    id: "stromleitung-beschaedigt",
    name: "Stromleitung beschädigt",
    section: 4,
    family: "technical",
    site: "street",
    size: 1,
    tags: ["electrical"],
  },
  {
    id: "technische-stoerung",
    name: "technische Störung",
    section: 4,
    family: "technical",
    site: "street",
    size: 1,
    tags: [],
  },
  {
    id: "vu-ohne-verletzte",
    name: "VU ohne Verletzte",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["uninjured"],
  },
  {
    id: "vu-mit-verletzten",
    name: "VU mit Verletzten",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury"],
  },
  {
    id: "vu-mit-mehreren-verletzten",
    name: "VU mit mehreren Verletzten",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "many"],
  },
  {
    id: "vu-mit-eingeklemmter-person",
    name: "VU mit eingeklemmter Person",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury", "trapped"],
  },
  {
    id: "vu-mit-feuer",
    name: "VU mit Feuer",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury", "fire"],
  },
  {
    id: "vu-mit-auslaufenden-betriebsstoffen",
    name: "VU mit auslaufenden Betriebsstoffen",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["spill"],
  },
  {
    id: "lkw-unfall",
    name: "Lkw-Unfall",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "trapped"],
  },
  {
    id: "busunfall",
    name: "Busunfall",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "many"],
  },
  {
    id: "motorradunfall",
    name: "Motorradunfall",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury", "vulnerable"],
  },
  {
    id: "fahrradunfall",
    name: "Fahrradunfall",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury", "vulnerable"],
  },
  {
    id: "mehrfachunfall",
    name: "Mehrfachunfall",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "many"],
  },
  {
    id: "massenkarambolage",
    name: "Massenkarambolage",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "many"],
  },
  {
    id: "fahrzeug-im-graben",
    name: "Fahrzeug im Graben",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury"],
  },
  {
    id: "fahrzeug-im-wasser",
    name: "Fahrzeug im Wasser",
    section: 5,
    family: "traffic",
    site: "water",
    size: 2,
    tags: ["injury", "shore"],
  },
  {
    id: "fahrzeug-gegen-gebaeude",
    name: "Fahrzeug gegen Gebäude",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury", "trapped", "collapse"],
  },
  {
    id: "fahrzeug-gegen-baum",
    name: "Fahrzeug gegen Baum",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury", "trapped"],
  },
  {
    id: "fahrzeug-gegen-laterne",
    name: "Fahrzeug gegen Laterne",
    section: 5,
    family: "traffic",
    site: "street",
    size: 2,
    tags: ["injury"],
  },
  {
    id: "fahrzeug-auf-bahnuebergang",
    name: "Fahrzeug auf Bahnübergang",
    section: 5,
    family: "traffic",
    site: "rail",
    size: 2,
    tags: ["rail"],
  },
  {
    id: "gefahrgutunfall-strasse",
    name: "Gefahrgutunfall Straße",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "chemical"],
  },
  {
    id: "lkw-verliert-ladung",
    name: "Lkw verliert Ladung",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["load"],
  },
  {
    id: "tankauflieger-beschaedigt",
    name: "Tankauflieger beschädigt",
    section: 5,
    family: "traffic",
    site: "street",
    size: 3,
    tags: ["injury", "spill"],
  },
  {
    id: "gasgeruch",
    name: "Gasgeruch",
    section: 6,
    family: "hazmat",
    site: "residential",
    size: 2,
    tags: ["gas"],
  },
  {
    id: "gasleck",
    name: "Gasleck",
    section: 6,
    family: "hazmat",
    site: "residential",
    size: 2,
    tags: ["gas"],
  },
  {
    id: "gasflasche-beschaedigt",
    name: "Gasflasche beschädigt",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 2,
    tags: ["gas"],
  },
  {
    id: "unbekannter-stoff",
    name: "unbekannter Stoff",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 2,
    tags: ["unknown"],
  },
  {
    id: "chemikalienleck",
    name: "Chemikalienleck",
    section: 6,
    family: "hazmat",
    site: "industrial",
    size: 2,
    tags: ["chemical"],
  },
  {
    id: "chemikalienaustritt",
    name: "Chemikalienaustritt",
    section: 6,
    family: "hazmat",
    site: "industrial",
    size: 3,
    tags: ["chemical"],
  },
  {
    id: "gefahrgut-lkw",
    name: "Gefahrgut-Lkw",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 2,
    tags: ["chemical"],
  },
  {
    id: "gefahrgut-bahn",
    name: "Gefahrgut-Bahn",
    section: 6,
    family: "hazmat",
    site: "rail",
    size: 3,
    tags: ["chemical", "rail"],
  },
  {
    id: "beschaedigter-tank",
    name: "beschädigter Tank",
    section: 6,
    family: "hazmat",
    site: "industrial",
    size: 3,
    tags: [],
  },
  {
    id: "unbekannte-daempfe",
    name: "unbekannte Dämpfe",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 2,
    tags: ["unknown"],
  },
  {
    id: "verdaechtiger-behaelter",
    name: "verdächtiger Behälter",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 2,
    tags: ["unknown"],
  },
  {
    id: "kontaminierte-person",
    name: "kontaminierte Person",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 3,
    tags: ["contamination", "injury"],
  },
  {
    id: "kontaminiertes-gebaeude",
    name: "kontaminiertes Gebäude",
    section: 6,
    family: "hazmat",
    site: "residential",
    size: 3,
    tags: ["contamination"],
  },
  {
    id: "gefahrstoff-auf-strasse",
    name: "Gefahrstoff auf Straße",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 2,
    tags: [],
  },
  {
    id: "gefahrstoff-in-betrieb",
    name: "Gefahrstoff in Betrieb",
    section: 6,
    family: "hazmat",
    site: "industrial",
    size: 2,
    tags: [],
  },
  {
    id: "dekontamination-erforderlich",
    name: "Dekontamination erforderlich",
    section: 6,
    family: "hazmat",
    site: "street",
    size: 3,
    tags: ["contamination"],
  },
  {
    id: "person-im-see",
    name: "Person im See",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 2,
    tags: ["shore", "injury"],
  },
  {
    id: "person-im-fluss",
    name: "Person im Fluss",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 2,
    tags: ["shore", "injury"],
  },
  {
    id: "person-im-wasser",
    name: "Person im Wasser",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 2,
    tags: ["shore", "injury"],
  },
  {
    id: "fahrzeug-im-wasser",
    name: "Fahrzeug im Wasser",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 3,
    tags: ["shore", "injury", "trapped"],
  },
  {
    id: "gekentertes-boot",
    name: "gekentertes Boot",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 3,
    tags: ["shore", "injury", "boat"],
  },
  {
    id: "bootsunfall",
    name: "Bootsunfall",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 3,
    tags: ["shore", "injury", "boat"],
  },
  {
    id: "vermisster-schwimmer",
    name: "vermisster Schwimmer",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 2,
    tags: ["shore", "injury", "search"],
  },
  {
    id: "eisunfall",
    name: "Eisunfall",
    section: 7,
    family: "water-rescue",
    site: "water",
    size: 2,
    tags: ["shore", "injury", "cold"],
  },
  {
    id: "hochwasser-keller",
    name: "Hochwasser Keller",
    section: 7,
    family: "flood",
    site: "residential",
    size: 2,
    tags: [],
  },
  {
    id: "hochwasser-strasse",
    name: "Hochwasser Straße",
    section: 7,
    family: "flood",
    site: "street",
    size: 2,
    tags: [],
  },
  {
    id: "hochwasser-wohngebiet",
    name: "Hochwasser Wohngebiet",
    section: 7,
    family: "flood",
    site: "residential",
    size: 3,
    tags: ["evacuation"],
  },
  {
    id: "ueberschwemmtes-gebaeude",
    name: "überschwemmtes Gebäude",
    section: 7,
    family: "flood",
    site: "residential",
    size: 2,
    tags: ["evacuation"],
  },
  {
    id: "deichproblem",
    name: "Deichproblem",
    section: 7,
    family: "flood",
    site: "residential",
    size: 3,
    tags: [],
  },
  {
    id: "baum-durch-sturm",
    name: "Baum durch Sturm",
    section: 7,
    family: "technical",
    site: "street",
    size: 2,
    tags: ["storm"],
  },
  {
    id: "dachschaden-durch-sturm",
    name: "Dachschaden durch Sturm",
    section: 7,
    family: "technical",
    site: "residential",
    size: 2,
    tags: ["storm", "height"],
  },
  {
    id: "strommast-durch-sturm",
    name: "Strommast durch Sturm",
    section: 7,
    family: "technical",
    site: "street",
    size: 2,
    tags: ["storm", "electrical"],
  },
  {
    id: "feld-waldbrand",
    name: "Feld-/Waldbrand",
    section: 7,
    family: "vegetation",
    site: "forest",
    size: 3,
    tags: ["vegetation"],
  },
  {
    id: "vegetationsbrand",
    name: "Vegetationsbrand",
    section: 7,
    family: "vegetation",
    site: "field",
    size: 3,
    tags: ["vegetation"],
  },
  {
    id: "bewusstlose-person",
    name: "Bewusstlose Person",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["unconscious"],
  },
  {
    id: "kreislaufproblem",
    name: "Kreislaufproblem",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "atemnot",
    name: "Atemnot",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["respiratory"],
  },
  {
    id: "brustschmerz",
    name: "Brustschmerz",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["cardiac", "pain"],
  },
  {
    id: "schlaganfallverdacht",
    name: "Schlaganfallverdacht",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["stroke"],
  },
  {
    id: "krampfanfall",
    name: "Krampfanfall",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["seizure"],
  },
  {
    id: "sturz",
    name: "Sturz",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["injury"],
  },
  {
    id: "schwerer-sturz",
    name: "schwerer Sturz",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["injury", "critical"],
  },
  {
    id: "kopfverletzung",
    name: "Kopfverletzung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["injury"],
  },
  {
    id: "schwere-blutung",
    name: "schwere Blutung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["injury", "critical", "bleeding"],
  },
  {
    id: "starke-schmerzen",
    name: "starke Schmerzen",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["pain"],
  },
  {
    id: "allergische-reaktion",
    name: "allergische Reaktion",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["allergy"],
  },
  {
    id: "schwere-allergische-reaktion",
    name: "schwere allergische Reaktion",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["critical", "allergy"],
  },
  {
    id: "vergiftung",
    name: "Vergiftung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["poison"],
  },
  {
    id: "intoxikation",
    name: "Intoxikation",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["poison"],
  },
  {
    id: "unterkuehlung",
    name: "Unterkühlung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["cold"],
  },
  {
    id: "ueberhitzung",
    name: "Überhitzung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["heat"],
  },
  {
    id: "dehydrierung",
    name: "Dehydrierung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["heat"],
  },
  {
    id: "verbrennung",
    name: "Verbrennung",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["injury", "burn"],
  },
  {
    id: "rauchgasexposition",
    name: "Rauchgasexposition",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["respiratory", "smoke"],
  },
  {
    id: "ertrinkungsunfall",
    name: "Ertrinkungsunfall",
    section: 8,
    family: "medical",
    site: "water",
    size: 1,
    tags: ["respiratory", "injury", "critical", "shore"],
  },
  {
    id: "badeunfall",
    name: "Badeunfall",
    section: 8,
    family: "medical",
    site: "water",
    size: 1,
    tags: ["injury", "shore"],
  },
  {
    id: "arbeitsunfall",
    name: "Arbeitsunfall",
    section: 8,
    family: "medical",
    site: "industrial",
    size: 1,
    tags: ["injury"],
  },
  {
    id: "sportunfall",
    name: "Sportunfall",
    section: 8,
    family: "medical",
    site: "public",
    size: 1,
    tags: ["injury"],
  },
  {
    id: "haeuslicher-notfall",
    name: "häuslicher Notfall",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "kindernotfall",
    name: "Kindernotfall",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["child"],
  },
  {
    id: "saeuglingsnotfall",
    name: "Säuglingsnotfall",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["critical", "infant"],
  },
  {
    id: "schwangerschaftsnotfall",
    name: "Schwangerschaftsnotfall",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["birth"],
  },
  {
    id: "geburt",
    name: "Geburt",
    section: 8,
    family: "medical",
    site: "residential",
    size: 1,
    tags: ["birth"],
  },
  {
    id: "reanimation",
    name: "Reanimation",
    section: 8,
    family: "medical",
    site: "residential",
    size: 2,
    tags: ["critical", "cpr"],
  },
  {
    id: "mehrere-verletzte",
    name: "mehrere Verletzte",
    section: 8,
    family: "medical",
    site: "residential",
    size: 3,
    tags: ["many"],
  },
  {
    id: "manv",
    name: "MANV",
    section: 8,
    family: "medical",
    site: "residential",
    size: 3,
    tags: ["many"],
  },
  {
    id: "medizinischer-notfall-in-oeffentlichem-gebaeude",
    name: "medizinischer Notfall in öffentlichem Gebäude",
    section: 8,
    family: "medical",
    site: "public",
    size: 1,
    tags: [],
  },
  {
    id: "einbruch",
    name: "Einbruch",
    section: 9,
    family: "police",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "einbruchalarm",
    name: "Einbruchalarm",
    section: 9,
    family: "police",
    site: "residential",
    size: 1,
    tags: [],
  },
  {
    id: "raub",
    name: "Raub",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["violence"],
  },
  {
    id: "diebstahl",
    name: "Diebstahl",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: [],
  },
  {
    id: "koerperverletzung",
    name: "Körperverletzung",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["violence", "injury"],
  },
  {
    id: "schlaegerei",
    name: "Schlägerei",
    section: 9,
    family: "police",
    site: "street",
    size: 2,
    tags: ["violence", "injury"],
  },
  {
    id: "messerangriff",
    name: "Messerangriff",
    section: 9,
    family: "police",
    site: "street",
    size: 2,
    tags: ["violence", "armed", "injury"],
  },
  {
    id: "bedrohung",
    name: "Bedrohung",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: [],
  },
  {
    id: "haeusliche-gewalt",
    name: "häusliche Gewalt",
    section: 9,
    family: "police",
    site: "residential",
    size: 1,
    tags: ["violence", "injury"],
  },
  {
    id: "vermisste-person",
    name: "vermisste Person",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["search"],
  },
  {
    id: "vermisstes-kind",
    name: "vermisstes Kind",
    section: 9,
    family: "police",
    site: "residential",
    size: 1,
    tags: ["search", "child"],
  },
  {
    id: "suizidandrohung",
    name: "Suizidandrohung",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["medical"],
  },
  {
    id: "gefaehrliche-person",
    name: "gefährliche Person",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: [],
  },
  {
    id: "bewaffnete-person",
    name: "bewaffnete Person",
    section: 9,
    family: "police",
    site: "street",
    size: 2,
    tags: ["armed"],
  },
  {
    id: "geisellage",
    name: "Geisellage",
    section: 9,
    family: "police",
    site: "street",
    size: 3,
    tags: ["armed", "many"],
  },
  {
    id: "amoklage",
    name: "Amoklage",
    section: 9,
    family: "police",
    site: "street",
    size: 3,
    tags: ["violence", "armed", "injury", "many"],
  },
  {
    id: "brandstiftung",
    name: "Brandstiftung",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["fire"],
  },
  {
    id: "sachbeschaedigung",
    name: "Sachbeschädigung",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: [],
  },
  {
    id: "fahrzeugflucht",
    name: "Fahrzeugflucht",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["traffic"],
  },
  {
    id: "verkehrskontrolle",
    name: "Verkehrskontrolle",
    section: 9,
    family: "police",
    site: "street",
    size: 1,
    tags: ["traffic"],
  },
  {
    id: "groessere-menschenansammlung",
    name: "größere Menschenansammlung",
    section: 9,
    family: "crowd",
    site: "public",
    size: 3,
    tags: ["public"],
  },
  {
    id: "absicherung",
    name: "Absicherung",
    section: 9,
    family: "crowd",
    site: "street",
    size: 2,
    tags: ["public"],
  },
  {
    id: "demonstration",
    name: "Demonstration",
    section: 9,
    family: "crowd",
    site: "public",
    size: 3,
    tags: ["public"],
  },
  {
    id: "veranstaltung",
    name: "Veranstaltung",
    section: 9,
    family: "crowd",
    site: "public",
    size: 2,
    tags: ["public"],
  },
  {
    id: "schwere-technische-bergung",
    name: "schwere technische Bergung",
    section: 10,
    family: "supply",
    site: "residential",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "ueberflutung",
    name: "Überflutung",
    section: 10,
    family: "flood",
    site: "residential",
    size: 2,
    tags: ["water"],
  },
  {
    id: "pumpeneinsatz",
    name: "Pumpeneinsatz",
    section: 10,
    family: "flood",
    site: "residential",
    size: 2,
    tags: ["water"],
  },
  {
    id: "stromversorgung",
    name: "Stromversorgung",
    section: 10,
    family: "supply",
    site: "residential",
    size: 2,
    tags: ["electrical", "evacuation"],
  },
  {
    id: "beleuchtung",
    name: "Beleuchtung",
    section: 10,
    family: "supply",
    site: "residential",
    size: 2,
    tags: ["light"],
  },
  {
    id: "truemmer",
    name: "Trümmer",
    section: 10,
    family: "supply",
    site: "construction",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "abstuetzung",
    name: "Abstützung",
    section: 10,
    family: "supply",
    site: "construction",
    size: 2,
    tags: ["collapse"],
  },
  {
    id: "versorgung-nach-stromausfall",
    name: "Versorgung nach Stromausfall",
    section: 10,
    family: "supply",
    site: "residential",
    size: 2,
    tags: ["electrical", "evacuation"],
  },
  {
    id: "katastrophenschutz",
    name: "Katastrophenschutz",
    section: 10,
    family: "supply",
    site: "residential",
    size: 3,
    tags: ["evacuation"],
  },
  {
    id: "grossschadenslage",
    name: "Großschadenslage",
    section: 10,
    family: "supply",
    site: "residential",
    size: 3,
    tags: ["evacuation"],
  },
];
