export type Org =
  | "Feuerwehr"
  | "Rettungsdienst"
  | "Polizei"
  | "THW"
  | "Wasserrettung"
  | "Infrastruktur";
export type Skills = Record<string, number>;
export const BALANCE = {
  start: 250000,
  hire: 600,
  training: 1800,
  trainingSeconds: 180,
  buildSeconds: 25,
  upgrade: 18000,
  upgradeSeconds: 60,
  offlineMax: 14400,
  missionInterval: 120,
  activeMax: 2,
  hospitalSeconds: 90,
  speed: 1,
  disconnectSeconds: 30,
};
export const capabilities: Record<string, string> = {
  fire: "Brandbekämpfung",
  water: "Löschwasser",
  rescue: "Technische Rettung",
  ladder: "Höhenrettung",
  command: "Einsatzleitung",
  hazmat: "Gefahrgut",
  air: "Atemschutz",
  medical: "Patientenversorgung",
  transport: "Patiententransport",
  doctor: "Notarzt",
  police: "Polizeiarbeit",
  crowd: "Absicherung",
  technical: "Bergung",
  pump: "Pumpen",
  logistics: "Logistik",
  diver: "Wasserrettung",
  boat: "Rettungsboot",
  flight: "Luftrettung",
};
export interface BuildingType {
  id: string;
  name: string;
  org: Org;
  price: number;
  slots: number;
  people: number;
  level: number;
  water?: boolean;
}
export const buildings: BuildingType[] = [
  {
    id: "fire",
    name: "Feuerwache",
    org: "Feuerwehr",
    price: 55000,
    slots: 4,
    people: 30,
    level: 1,
  },
  {
    id: "ems",
    name: "Rettungswache",
    org: "Rettungsdienst",
    price: 42000,
    slots: 4,
    people: 16,
    level: 2,
  },
  {
    id: "police",
    name: "Polizeiwache",
    org: "Polizei",
    price: 40000,
    slots: 4,
    people: 20,
    level: 2,
  },
  {
    id: "thw",
    name: "THW-Unterkunft",
    org: "THW",
    price: 62000,
    slots: 4,
    people: 32,
    level: 3,
  },
  {
    id: "water",
    name: "Wasserrettungsstation",
    org: "Wasserrettung",
    price: 48000,
    slots: 4,
    people: 20,
    level: 3,
    water: true,
  },
  {
    id: "hospital",
    name: "Krankenhaus",
    org: "Infrastruktur",
    price: 100000,
    slots: 0,
    people: 0,
    level: 3,
  },
  {
    id: "school",
    name: "Ausbildungszentrum",
    org: "Infrastruktur",
    price: 35000,
    slots: 0,
    people: 0,
    level: 2,
  },
  {
    id: "heli",
    name: "Rettungshubschrauberstation",
    org: "Rettungsdienst",
    price: 95000,
    slots: 2,
    people: 12,
    level: 4,
  },
];
export interface VehicleType {
  id: string;
  name: string;
  home: string;
  price: number;
  crew: number;
  training: string;
  speed: number;
  skills: Skills;
  capacity: number;
  level: number;
  mode: "road" | "air" | "water";
}
const v = (
  id: string,
  name: string,
  home: string,
  price: number,
  crew: number,
  skills: Skills,
  level = 1,
  training = "",
  mode: VehicleType["mode"] = "road",
  capacity = 0,
): VehicleType => ({
  id,
  name,
  home,
  price,
  crew,
  skills,
  level,
  training,
  mode,
  capacity,
  speed: mode === "air" ? 180 : mode === "water" ? 30 : 60,
});
export const vehicles: VehicleType[] = [
  v("tsf", "TSF-W", "fire", 18000, 6, { fire: 1, water: 1 }),
  v("lf", "LF 20", "fire", 30000, 9, { fire: 2, water: 2, pump: 1 }),
  v("hlf", "HLF 20", "fire", 45000, 9, { fire: 2, rescue: 2, water: 1 }, 2),
  v("tlf", "TLF 4000", "fire", 35000, 3, { fire: 1, water: 4 }, 2),
  v("dlk", "DLK 23", "fire", 48000, 3, { ladder: 2 }, 2, "Drehleiter"),
  v("elw", "ELW 1", "fire", 22000, 2, { command: 2 }, 2, "Führung"),
  v("rw", "RW", "fire", 43000, 3, { rescue: 3, technical: 1 }, 3, "Bergung"),
  v("haz", "GW-Gefahrgut", "fire", 48000, 3, { hazmat: 3 }, 3, "Gefahrgut"),
  v("air", "GW-Atemschutz", "fire", 30000, 3, { air: 4 }, 3, "Atemschutz"),
  v(
    "rtw",
    "RTW",
    "ems",
    25000,
    2,
    { medical: 2, transport: 1 },
    2,
    "",
    "road",
    1,
  ),
  v(
    "ktw",
    "KTW",
    "ems",
    16000,
    2,
    { medical: 1, transport: 1 },
    2,
    "",
    "road",
    1,
  ),
  v("nef", "NEF", "ems", 28000, 2, { doctor: 1, medical: 1 }, 2, "Notarzt"),
  v(
    "rth",
    "RTH",
    "heli",
    110000,
    3,
    { medical: 2, doctor: 1, transport: 1, flight: 1 },
    4,
    "Luftrettung",
    "air",
    1,
  ),
  v(
    "fustw",
    "Funkstreifenwagen",
    "police",
    16000,
    2,
    { police: 2, crowd: 1 },
    2,
  ),
  v("pmtw", "Polizei-MTW", "police", 24000, 6, { police: 1, crowd: 4 }, 2),
  v("gkw", "GKW", "thw", 35000, 9, { technical: 3, rescue: 1 }, 3, "Bergung"),
  v(
    "mzgw",
    "MzGW",
    "thw",
    32000,
    6,
    { technical: 1, pump: 3, logistics: 2 },
    3,
  ),
  v("tmtw", "THW-MTW", "thw", 18000, 6, { logistics: 3, command: 1 }, 3),
  v(
    "gww",
    "GW-Wasserrettung",
    "water",
    28000,
    4,
    { diver: 2, rescue: 1 },
    3,
    "Wasserrettung",
  ),
  v(
    "boat",
    "Rettungsboot",
    "water",
    18000,
    2,
    { boat: 2, diver: 1 },
    3,
    "Wasserrettung",
    "water",
  ),
];
export interface Template {
  id: string;
  name: string;
  org: Org | "Verbund";
  requirements: Skills;
  seconds: number;
  reward: number;
  patients: number;
  level: number;
  water: boolean;
  description: string;
}
const m = (
  id: string,
  name: string,
  org: Template["org"],
  requirements: Skills,
  seconds: number,
  reward: number,
  patients = 0,
  level = 1,
  water = false,
): Template => ({
  id,
  name,
  org,
  requirements,
  seconds,
  reward,
  patients,
  level,
  water,
  description: `${name} in der Region Falkenried. Lage erkunden, benötigte Kräfte bereitstellen und die Gefahrenstelle sichern.`,
});
export const missions: Template[] = [
  m("bin", "Müllbehälterbrand", "Feuerwehr", { fire: 1 }, 20, 6500),
  m("car", "Pkw-Brand", "Feuerwehr", { fire: 1, water: 1 }, 30, 8000),
  m("shed", "Gartenlaubenbrand", "Feuerwehr", { fire: 2 }, 40, 10000),
  m("field", "Flächenbrand", "Feuerwehr", { fire: 2, water: 3 }, 55, 14000),
  m(
    "flat",
    "Wohnungsbrand",
    "Feuerwehr",
    { fire: 3, ladder: 1 },
    65,
    18000,
    0,
    2,
  ),
  m(
    "roof",
    "Dachstuhlbrand",
    "Feuerwehr",
    { fire: 4, ladder: 2, water: 2 },
    80,
    24000,
    0,
    2,
  ),
  m(
    "factory",
    "Industriebrand",
    "Feuerwehr",
    { fire: 6, water: 4, command: 2, air: 2 },
    110,
    48000,
    0,
    3,
  ),
  m("tree", "Baum auf Straße", "Feuerwehr", { rescue: 1 }, 30, 7500, 0, 2),
  m("cellar", "Keller unter Wasser", "Feuerwehr", { pump: 1 }, 45, 9000),
  m(
    "chemical",
    "Gefahrstoffaustritt",
    "Feuerwehr",
    { hazmat: 2, fire: 1, command: 1 },
    80,
    23000,
    0,
    3,
  ),
  m(
    "smoke",
    "Rauchentwicklung im Tunnel",
    "Feuerwehr",
    { fire: 2, air: 3, command: 1 },
    70,
    21000,
    0,
    3,
  ),
  m(
    "silo",
    "Silobrand",
    "Feuerwehr",
    { fire: 3, water: 4, ladder: 1, air: 1 },
    100,
    35000,
    0,
    3,
  ),
  m(
    "sick",
    "Medizinischer Notfall",
    "Rettungsdienst",
    { medical: 2, transport: 1 },
    25,
    8500,
    1,
    2,
  ),
  m(
    "transfer",
    "Krankentransport",
    "Rettungsdienst",
    { medical: 1, transport: 1 },
    15,
    6000,
    1,
    2,
  ),
  m(
    "heart",
    "Herz-Kreislauf-Stillstand",
    "Rettungsdienst",
    { medical: 3, doctor: 1, transport: 1 },
    50,
    14000,
    1,
    2,
  ),
  m(
    "fall",
    "Sturz im Treppenhaus",
    "Rettungsdienst",
    { medical: 2, rescue: 1, transport: 1 },
    40,
    11000,
    1,
    2,
  ),
  m(
    "birth",
    "Beginnende Geburt",
    "Rettungsdienst",
    { medical: 2, doctor: 1, transport: 1 },
    35,
    12000,
    1,
    2,
  ),
  m(
    "sport",
    "Sportunfall mit zwei Verletzten",
    "Rettungsdienst",
    { medical: 4, transport: 2 },
    45,
    17000,
    2,
    2,
  ),
  m(
    "remote",
    "Notfall am Waldhang",
    "Rettungsdienst",
    { flight: 1, doctor: 1, medical: 2, transport: 1 },
    45,
    19000,
    1,
    4,
  ),
  m(
    "care",
    "Evakuierung Pflegewohnung",
    "Rettungsdienst",
    { medical: 3, transport: 3 },
    60,
    22000,
    3,
    2,
  ),
  m("traffic", "Verkehrsbehinderung", "Polizei", { police: 1 }, 20, 6500, 0, 2),
  m("theft", "Ladendiebstahl", "Polizei", { police: 2 }, 25, 7500, 0, 2),
  m(
    "burglary",
    "Einbruch mit Spurensicherung",
    "Polizei",
    { police: 4 },
    45,
    11500,
    0,
    2,
  ),
  m(
    "match",
    "Absicherung Sportveranstaltung",
    "Polizei",
    { crowd: 4 },
    65,
    14000,
    0,
    2,
  ),
  m(
    "search",
    "Vermisste Person im Ortskern",
    "Polizei",
    { police: 5, crowd: 1 },
    60,
    16000,
    0,
    2,
  ),
  m(
    "demo",
    "Versammlung am Rathaus",
    "Polizei",
    { crowd: 6, police: 3 },
    75,
    22000,
    0,
    2,
  ),
  m(
    "roadblock",
    "Straßensperre nach Hangrutsch",
    "Polizei",
    { police: 2, crowd: 3 },
    45,
    12500,
    0,
    2,
  ),
  m(
    "fair",
    "Besucherlenkung Stadtfest",
    "Polizei",
    { crowd: 8, command: 1 },
    80,
    25000,
    0,
    3,
  ),
  m("debris", "Trümmer auf Fahrbahn", "THW", { technical: 2 }, 45, 13000, 0, 3),
  m(
    "pump",
    "Überflutete Unterführung",
    "THW",
    { pump: 3, technical: 1 },
    65,
    18000,
    0,
    3,
  ),
  m(
    "supply",
    "Notversorgung nach Stromausfall",
    "THW",
    { logistics: 3, technical: 1 },
    70,
    21000,
    0,
    3,
  ),
  m(
    "shore",
    "Person am Ufer vermisst",
    "Wasserrettung",
    { diver: 2 },
    50,
    15000,
    0,
    3,
    true,
  ),
  m(
    "capsize",
    "Gekentertes Ruderboot",
    "Wasserrettung",
    { boat: 2, diver: 2 },
    60,
    20000,
    0,
    3,
    true,
  ),
  m(
    "flood",
    "Deichsicherung",
    "THW",
    { pump: 3, logistics: 4, technical: 3 },
    100,
    38000,
    0,
    3,
  ),
  m(
    "crash",
    "Verkehrsunfall mit eingeklemmter Person",
    "Verbund",
    { rescue: 2, medical: 2, transport: 1, police: 2 },
    65,
    23000,
    1,
    2,
  ),
  m(
    "bus",
    "Busunfall",
    "Verbund",
    { rescue: 3, medical: 6, transport: 3, crowd: 4, command: 1 },
    100,
    50000,
    3,
    3,
  ),
  m(
    "warehouse",
    "Lagerhallenbrand mit Verletzten",
    "Verbund",
    { fire: 4, water: 4, medical: 4, transport: 2, police: 2 },
    90,
    40000,
    2,
    2,
  ),
  m(
    "waterrescue",
    "Wasserrettung mit Reanimation",
    "Verbund",
    { boat: 2, diver: 2, doctor: 1, medical: 2, transport: 1 },
    80,
    30000,
    1,
    3,
    true,
  ),
  m(
    "collapse",
    "Gebäudeeinsturz",
    "Verbund",
    { technical: 4, rescue: 3, medical: 4, transport: 2, command: 2, crowd: 2 },
    120,
    60000,
    2,
    3,
  ),
  m(
    "rail",
    "Gefahrgutunfall am Güterbahnhof",
    "Verbund",
    {
      hazmat: 3,
      fire: 3,
      technical: 3,
      medical: 2,
      transport: 1,
      crowd: 4,
      air: 2,
    },
    130,
    68000,
    1,
    3,
  ),
];
export const bt = (id: string) => {
  const x = buildings.find((b) => b.id === id);
  if (!x) throw Error("Unbekannter Gebäudetyp");
  return x;
};
export const extensions = [
  {
    id: "technical",
    home: "fire",
    name: "Technische Hilfeleistung",
    price: 12000,
    level: 3,
    types: ["rw"],
  },
  {
    id: "hazmat",
    home: "fire",
    name: "Gefahrgut-Erweiterung",
    price: 16000,
    level: 3,
    types: ["haz"],
  },
  {
    id: "air",
    home: "fire",
    name: "Atemschutzwerkstatt",
    price: 12000,
    level: 3,
    types: ["air"],
  },
  {
    id: "doctor",
    home: "ems",
    name: "Notarztstandort",
    price: 12000,
    level: 2,
    types: ["nef"],
  },
];
export const vt = (id: string) => {
  const x = vehicles.find((v) => v.id === id);
  if (!x) throw Error("Unbekannter Fahrzeugtyp");
  return x;
};
export const mt = (id: string) => {
  const x = missions.find((m) => m.id === id);
  if (!x) throw Error("Unbekannte Einsatzart");
  return x;
};
