import { WORLD_NAME, IS_GERMANY } from "./world-choice";
import { unlockLevel } from "./progression";
import { incidentVariants } from "./catalog/incident-variants";
import type { IncidentProfile } from "./catalog/incident-profile";
export type Org =
  | "Feuerwehr"
  | "Rettungsdienst"
  | "Polizei"
  | "THW"
  | "Wasserrettung"
  | "Infrastruktur";
export type Skills = Record<string, number>;
export const BALANCE = {
  start: 250000,
  hire: 600,
  training: 1800,
  trainingSeconds: 180,
  buildSeconds: 25,
  upgrade: 18000,
  upgradeSeconds: 60,
  offlineMax: 14400,
  missionInterval: 120,
  hospitalSeconds: 90,
  speed: 1,
  disconnectSeconds: 30,
};
export const capabilities: Record<string, string> = {
  fire: "Brandbekämpfung",
  water: "Löschwasser",
  rescue: "Technische Rettung",
  ladder: "Höhenrettung",
  command: "Einsatzleitung",
  hazmat: "Gefahrgut",
  air: "Atemschutz",
  medical: "Patientenversorgung",
  transport: "Patiententransport",
  doctor: "Notarzt",
  police: "Polizeiarbeit",
  crowd: "Absicherung",
  technical: "Bergung",
  pump: "Pumpen",
  logistics: "Logistik",
  diver: "Wasserrettung",
  boat: "Rettungsboot",
  flight: "Luftrettung",
  foam: "Schaummittelversorgung",
  measure: "Gefahrstoffmessung",
  decon: "Dekontamination",
  intensive: "Intensivversorgung",
  medicalCommand: "Rettungsdienstführung",
  care: "Betreuung",
  power: "Notstromversorgung",
  lighting: "Beleuchtung",
};
export interface BuildingType {
  id: string;
  name: string;
  org: Org;
  price: number;
  slots: number;
  people: number;
  level: number;
  water?: boolean;
}
export const buildings: BuildingType[] = [
  {
    id: "fire",
    name: "Feuerwache",
    org: "Feuerwehr",
    price: 55000,
    slots: 4,
    people: 30,
    level: 1,
  },
  {
    id: "ems",
    name: "Rettungswache",
    org: "Rettungsdienst",
    price: 42000,
    slots: 4,
    people: 16,
    level: 2,
  },
  {
    id: "police",
    name: "Polizeiwache",
    org: "Polizei",
    price: 40000,
    slots: 4,
    people: 20,
    level: 2,
  },
  {
    id: "thw",
    name: "THW-Unterkunft",
    org: "THW",
    price: 62000,
    slots: 4,
    people: 32,
    level: 3,
  },
  {
    id: "water",
    name: "Wasserrettungsstation",
    org: "Wasserrettung",
    price: 48000,
    slots: 4,
    people: 20,
    level: 3,
    water: true,
  },
  {
    id: "hospital",
    name: "Krankenhaus",
    org: "Infrastruktur",
    price: 100000,
    slots: 0,
    people: 0,
    level: 3,
  },
  {
    id: "school",
    name: "Ausbildungszentrum",
    org: "Infrastruktur",
    price: 35000,
    slots: 0,
    people: 0,
    level: 2,
  },
  {
    id: "heli",
    name: "Rettungshubschrauberstation",
    org: "Rettungsdienst",
    price: 95000,
    slots: 2,
    people: 12,
    level: 4,
  },
];
export interface VehicleType {
  id: string;
  name: string;
  home: string;
  price: number;
  crew: number;
  crewMinimum?: number;
  training: string;
  speed: number;
  skills: Skills;
  capacity: number;
  level: number;
  mode: "road" | "air" | "water";
}
const v = (
  id: string,
  name: string,
  home: string,
  price: number,
  crew: number,
  skills: Skills,
  level = 1,
  training = "",
  mode: VehicleType["mode"] = "road",
  capacity = 0,
): VehicleType => ({
  id,
  name,
  home,
  price,
  crew,
  skills,
  level: unlockLevel("vehicle", id) || level,
  training,
  mode,
  capacity,
  speed:
    mode === "air"
      ? 180
      : mode === "water"
        ? 30
        : ["nef", "fustw", "elw"].includes(id)
          ? 120
          : ["rtw", "ktw", "pmtw", "tmtw"].includes(id)
            ? 110
            : 90,
});
export const vehicles: VehicleType[] = [
  v("tsf", "TSF-W", "fire", 18000, 6, { fire: 1, water: 1 }),
  v("lf", "LF 20", "fire", 30000, 9, { fire: 2, water: 2, pump: 1 }),
  v("hlf", "HLF 20", "fire", 45000, 9, { fire: 2, rescue: 2, water: 1 }, 2),
  v("tlf", "TLF 4000", "fire", 35000, 3, { fire: 1, water: 4 }, 2),
  v("dlk", "DLK 23", "fire", 48000, 3, { ladder: 2 }, 2, "Drehleiter"),
  v("elw", "ELW 1", "fire", 22000, 2, { command: 2 }, 2, "Führung"),
  v("rw", "RW", "fire", 43000, 3, { rescue: 3, technical: 1 }, 3, "Bergung"),
  v("haz", "GW-Gefahrgut", "fire", 48000, 3, { hazmat: 3 }, 3, "Gefahrgut"),
  v("air", "GW-Atemschutz", "fire", 30000, 3, { air: 4 }, 3, "Atemschutz"),
  v(
    "rtw",
    "RTW",
    "ems",
    25000,
    2,
    { medical: 2, transport: 1 },
    2,
    "",
    "road",
    1,
  ),
  v(
    "ktw",
    "KTW",
    "ems",
    16000,
    2,
    { medical: 1, transport: 1 },
    2,
    "",
    "road",
    1,
  ),
  v("nef", "NEF", "ems", 28000, 2, { doctor: 1, medical: 1 }, 2, "Notarzt"),
  v(
    "rth",
    "RTH",
    "heli",
    110000,
    3,
    { medical: 2, doctor: 1, transport: 1, flight: 1 },
    4,
    "Luftrettung",
    "air",
    1,
  ),
  v(
    "fustw",
    "Funkstreifenwagen",
    "police",
    16000,
    2,
    { police: 2, crowd: 1 },
    2,
  ),
  v("pmtw", "Polizei-MTW", "police", 24000, 6, { police: 1, crowd: 4 }, 2),
  v("gkw", "GKW", "thw", 35000, 9, { technical: 3, rescue: 1 }, 3, "Bergung"),
  v(
    "mzgw",
    "MzGW",
    "thw",
    32000,
    6,
    { technical: 1, pump: 3, logistics: 2 },
    3,
  ),
  v("tmtw", "THW-MTW", "thw", 18000, 6, { logistics: 3, command: 1 }, 3),
  v(
    "gww",
    "GW-Wasserrettung",
    "water",
    28000,
    4,
    { diver: 2, rescue: 1 },
    3,
    "Wasserrettung",
  ),
  v(
    "boat",
    IS_GERMANY ? "Zugfahrzeug mit Rettungsboot (MZB)" : "Rettungsboot",
    "water",
    IS_GERMANY ? 36000 : 18000,
    IS_GERMANY ? 4 : 2,
    { boat: 2, diver: 1 },
    3,
    "Wasserrettung",
    IS_GERMANY ? "road" : "water",
  ),
  v("lf10", "LF 10", "fire", 24500, 9, { fire: 2, water: 1, pump: 1 }, 2),
  v("hlf10", "HLF 10", "fire", 36500, 9, { fire: 1, rescue: 2, water: 1 }, 2),
  v("tlf2000", "TLF 2000", "fire", 26500, 3, { fire: 1, water: 2 }, 2),
  v("tlf3000", "TLF 3000", "fire", 31000, 3, { fire: 1, water: 3 }, 2),
  v(
    "elw2",
    "ELW 2",
    "fire",
    84000,
    4,
    { command: 5, logistics: 1 },
    3,
    "Führung",
  ),
  v("kdow", "KdoW", "fire", 17000, 1, { command: 1 }, 2, "Führung"),
  v("vrw", "VRW", "fire", 25000, 3, { rescue: 2 }, 2, "Bergung"),
  v("gwl", "GW-L", "fire", 37000, 3, { logistics: 4, lighting: 1 }, 3),
  v("gwmess", "GW-Mess", "fire", 42000, 3, { measure: 3 }, 3, "Gefahrgut"),
  v(
    "gwt",
    "GW-T",
    "fire",
    38000,
    3,
    { technical: 2, rescue: 1, power: 1 },
    3,
    "Bergung",
  ),
  // Every AB entry is a complete road-going WLF + loaded container combination.
  v(
    "abruest",
    "WLF mit AB-Rüst",
    "fire",
    76000,
    2,
    { rescue: 4, technical: 3 },
    3,
    "Bergung",
  ),
  v(
    "abwasser",
    "WLF mit AB-Wasser",
    "fire",
    69000,
    2,
    { water: 8, pump: 1 },
    3,
  ),
  v(
    "abschaum",
    "WLF mit AB-Schaum",
    "fire",
    74000,
    2,
    { foam: 5, water: 2 },
    3,
  ),
  v(
    "abatem",
    "WLF mit AB-Atemschutz",
    "fire",
    71000,
    2,
    { air: 8, logistics: 1 },
    3,
    "Atemschutz",
  ),
  v(
    "abgefahrgut",
    "WLF mit AB-Gefahrgut",
    "fire",
    85000,
    3,
    { hazmat: 5, measure: 1 },
    3,
    "Gefahrgut",
  ),
  v("sw", "Schlauchwagen SW 2000", "fire", 35000, 3, { water: 4, pump: 3 }, 3),
  v(
    "dekonp",
    "Dekon-P",
    "fire",
    59000,
    6,
    { decon: 4, logistics: 1 },
    3,
    "Gefahrgut",
  ),
  v(
    "grtw",
    "GRTW",
    "ems",
    115000,
    4,
    { medical: 8, transport: 6, care: 2 },
    3,
    "Rettungsdienst",
    "road",
    6,
  ),
  v(
    "naw",
    "NAW",
    "ems",
    52000,
    3,
    { medical: 2, doctor: 1, transport: 1 },
    3,
    "Notarzt",
    "road",
    1,
  ),
  v(
    "itw",
    "ITW",
    "ems",
    89000,
    3,
    { medical: 3, doctor: 1, intensive: 1, transport: 1 },
    3,
    "Intensivtransport",
    "road",
    1,
  ),
  v(
    "ith",
    "ITH",
    "heli",
    170000,
    4,
    { medical: 3, doctor: 1, intensive: 1, transport: 1, flight: 1 },
    4,
    "Intensivtransport",
    "air",
    1,
  ),
  v(
    "rtwxl",
    "RTW – erweiterte Versorgung",
    "ems",
    39000,
    3,
    { medical: 3, transport: 1 },
    2,
    "Rettungsdienst",
    "road",
    1,
  ),
  v(
    "ktwb",
    "KTW-B – zwei Transportplätze",
    "ems",
    23000,
    2,
    { medical: 1, transport: 2 },
    2,
    "",
    "road",
    2,
  ),
  v(
    "mzf",
    "MZF Rettungsdienst",
    "ems",
    27000,
    2,
    { medical: 1, transport: 1, logistics: 2 },
    2,
    "",
    "road",
    1,
  ),
  v(
    "elrd",
    "ELRD",
    "ems",
    34000,
    2,
    { medicalCommand: 2, command: 1 },
    3,
    "Führung",
  ),
  v(
    "orgl",
    "OrgL Rettungsdienst",
    "ems",
    37000,
    2,
    { medicalCommand: 3, logistics: 1 },
    3,
    "Führung",
  ),
  v(
    "lna",
    "LNA",
    "ems",
    43000,
    2,
    { medicalCommand: 2, doctor: 2 },
    3,
    "Notarzt",
  ),
  v(
    "segrtw",
    "SEG-RTW",
    "ems",
    21500,
    3,
    { medical: 2, transport: 1, care: 1 },
    2,
    "Rettungsdienst",
    "road",
    1,
  ),
  v(
    "gwsan",
    "GW-San",
    "ems",
    58000,
    6,
    { medical: 6, care: 3, logistics: 1 },
    3,
    "Rettungsdienst",
  ),
  v(
    "segbetreuung",
    "SEG-Betreuung",
    "ems",
    36000,
    6,
    { care: 6, logistics: 3 },
    3,
  ),
];
for (const type of vehicles)
  type.crewMinimum =
    type.id === "tsf"
      ? 4
      : ["lf", "lf10", "hlf", "hlf10"].includes(type.id)
        ? 6
        : type.crew;
export interface Template {
  id: string;
  name: string;
  org: Org | "Verbund" | "Unbekannt";
  requirements: Skills;
  seconds: number;
  reward: number;
  patients: number;
  level: number;
  water: boolean;
  description: string;
  profile?: IncidentProfile;
}
const m = (
  id: string,
  name: string,
  org: Template["org"],
  requirements: Skills,
  seconds: number,
  reward: number,
  patients = 0,
  level = 1,
  water = false,
): Template => ({
  id,
  name,
  org,
  requirements,
  seconds,
  reward,
  patients,
  level,
  water,
  description: `${name} in der Region ${WORLD_NAME}. Lage erkunden, benötigte Kräfte bereitstellen und die Gefahrenstelle sichern.`,
});
export const missions: Template[] = [
  m("bin", "Müllbehälterbrand", "Feuerwehr", { fire: 1 }, 20, 6500),
  m("car", "Pkw-Brand", "Feuerwehr", { fire: 1, water: 1 }, 30, 8000),
  m("shed", "Gartenlaubenbrand", "Feuerwehr", { fire: 2 }, 40, 10000),
  m("field", "Flächenbrand", "Feuerwehr", { fire: 2, water: 3 }, 55, 14000),
  m(
    "flat",
    "Wohnungsbrand",
    "Feuerwehr",
    { fire: 3, ladder: 1 },
    65,
    18000,
    0,
    2,
  ),
  m(
    "roof",
    "Dachstuhlbrand",
    "Feuerwehr",
    { fire: 4, ladder: 2, water: 2 },
    80,
    24000,
    0,
    2,
  ),
  m(
    "factory",
    "Industriebrand",
    "Feuerwehr",
    { fire: 6, water: 4, command: 2, air: 2 },
    110,
    48000,
    0,
    3,
  ),
  m("tree", "Baum auf Straße", "Feuerwehr", { rescue: 1 }, 30, 7500, 0, 2),
  m("cellar", "Keller unter Wasser", "Feuerwehr", { pump: 1 }, 45, 9000),
  m(
    "chemical",
    "Gefahrstoffaustritt",
    "Feuerwehr",
    { hazmat: 2, fire: 1, command: 1 },
    80,
    23000,
    0,
    3,
  ),
  m(
    "smoke",
    "Rauchentwicklung im Tunnel",
    "Feuerwehr",
    { fire: 2, air: 3, command: 1 },
    70,
    21000,
    0,
    3,
  ),
  m(
    "silo",
    "Silobrand",
    "Feuerwehr",
    { fire: 3, water: 4, ladder: 1, air: 1 },
    100,
    35000,
    0,
    3,
  ),
  m(
    "sick",
    "Medizinischer Notfall",
    "Rettungsdienst",
    { medical: 2, transport: 1 },
    25,
    8500,
    1,
    2,
  ),
  m(
    "transfer",
    "Krankentransport",
    "Rettungsdienst",
    { medical: 1, transport: 1 },
    15,
    6000,
    1,
    2,
  ),
  m(
    "heart",
    "Herz-Kreislauf-Stillstand",
    "Rettungsdienst",
    { medical: 3, doctor: 1, transport: 1 },
    50,
    14000,
    1,
    2,
  ),
  m(
    "fall",
    "Sturz im Treppenhaus",
    "Rettungsdienst",
    { medical: 2, rescue: 1, transport: 1 },
    40,
    11000,
    1,
    2,
  ),
  m(
    "birth",
    "Beginnende Geburt",
    "Rettungsdienst",
    { medical: 2, doctor: 1, transport: 1 },
    35,
    12000,
    1,
    2,
  ),
  m(
    "sport",
    "Sportunfall mit zwei Verletzten",
    "Rettungsdienst",
    { medical: 4, transport: 2 },
    45,
    17000,
    2,
    2,
  ),
  m(
    "remote",
    "Notfall am Waldhang",
    "Rettungsdienst",
    { flight: 1, doctor: 1, medical: 2, transport: 1 },
    45,
    19000,
    1,
    4,
  ),
  m(
    "care",
    "Evakuierung Pflegewohnung",
    "Rettungsdienst",
    { medical: 3, transport: 3 },
    60,
    22000,
    3,
    2,
  ),
  m("traffic", "Verkehrsbehinderung", "Polizei", { police: 1 }, 20, 6500, 0, 2),
  m("theft", "Ladendiebstahl", "Polizei", { police: 2 }, 25, 7500, 0, 2),
  m(
    "burglary",
    "Einbruch mit Spurensicherung",
    "Polizei",
    { police: 4 },
    45,
    11500,
    0,
    2,
  ),
  m(
    "match",
    "Absicherung Sportveranstaltung",
    "Polizei",
    { crowd: 4 },
    65,
    14000,
    0,
    2,
  ),
  m(
    "search",
    "Vermisste Person im Ortskern",
    "Polizei",
    { police: 5, crowd: 1 },
    60,
    16000,
    0,
    2,
  ),
  m(
    "demo",
    "Versammlung am Rathaus",
    "Polizei",
    { crowd: 6, police: 3 },
    75,
    22000,
    0,
    2,
  ),
  m(
    "roadblock",
    "Straßensperre nach Hangrutsch",
    "Polizei",
    { police: 2, crowd: 3 },
    45,
    12500,
    0,
    2,
  ),
  m(
    "fair",
    "Besucherlenkung Stadtfest",
    "Polizei",
    { crowd: 8, command: 1 },
    80,
    25000,
    0,
    3,
  ),
  m("debris", "Trümmer auf Fahrbahn", "THW", { technical: 2 }, 45, 13000, 0, 3),
  m(
    "pump",
    "Überflutete Unterführung",
    "THW",
    { pump: 3, technical: 1 },
    65,
    18000,
    0,
    3,
  ),
  m(
    "supply",
    "Notversorgung nach Stromausfall",
    "THW",
    { logistics: 3, technical: 1 },
    70,
    21000,
    0,
    3,
  ),
  m(
    "shore",
    "Person am Ufer vermisst",
    "Wasserrettung",
    { diver: 2 },
    50,
    15000,
    0,
    3,
    true,
  ),
  m(
    "capsize",
    "Gekentertes Ruderboot",
    "Wasserrettung",
    { boat: 2, diver: 2 },
    60,
    20000,
    0,
    3,
    true,
  ),
  m(
    "flood",
    "Deichsicherung",
    "THW",
    { pump: 3, logistics: 4, technical: 3 },
    100,
    38000,
    0,
    3,
  ),
  m(
    "crash",
    "Verkehrsunfall mit eingeklemmter Person",
    "Verbund",
    { rescue: 2, medical: 2, transport: 1, police: 2 },
    65,
    23000,
    1,
    2,
  ),
  m(
    "bus",
    "Busunfall",
    "Verbund",
    { rescue: 3, medical: 6, transport: 3, crowd: 4, command: 1 },
    100,
    50000,
    3,
    3,
  ),
  m(
    "warehouse",
    "Lagerhallenbrand mit Verletzten",
    "Verbund",
    { fire: 4, water: 4, medical: 4, transport: 2, police: 2 },
    90,
    40000,
    2,
    2,
  ),
  m(
    "waterrescue",
    "Wasserrettung mit Reanimation",
    "Verbund",
    { boat: 2, diver: 2, doctor: 1, medical: 2, transport: 1 },
    80,
    30000,
    1,
    3,
    true,
  ),
  m(
    "collapse",
    "Gebäudeeinsturz",
    "Verbund",
    { technical: 4, rescue: 3, medical: 4, transport: 2, command: 2, crowd: 2 },
    120,
    60000,
    2,
    3,
  ),
  m(
    "rail",
    "Gefahrgutunfall am Güterbahnhof",
    "Verbund",
    {
      hazmat: 3,
      fire: 3,
      technical: 3,
      medical: 2,
      transport: 1,
      crowd: 4,
      air: 2,
    },
    130,
    68000,
    1,
    3,
  ),
  m(
    "bma-false",
    "Brandmeldeanlage – Fehlalarm",
    "Feuerwehr",
    { fire: 1 },
    30,
    5000,
  ),
  ...incidentVariants,
];
export const bt = (id: string) => {
  const x = buildings.find((b) => b.id === id);
  if (!x) throw Error("Unbekannter Gebäudetyp");
  return x;
};
export const extensions = [
  {
    id: "technical",
    home: "fire",
    name: "Technische Hilfeleistung",
    price: 12000,
    level: 3,
    types: ["rw"],
  },
  {
    id: "hazmat",
    home: "fire",
    name: "Gefahrgut-Erweiterung",
    price: 16000,
    level: 3,
    types: ["haz"],
  },
  {
    id: "air",
    home: "fire",
    name: "Atemschutzwerkstatt",
    price: 12000,
    level: 3,
    types: ["air"],
  },
  {
    id: "doctor",
    home: "ems",
    name: "Notarztstandort",
    price: 12000,
    level: 2,
    types: ["nef"],
  },
];
for (const b of buildings) b.level = unlockLevel("building", b.id);
for (const e of extensions) e.level = unlockLevel("extension", e.id);
export const vt = (id: string) => {
  const x = vehicles.find((v) => v.id === id);
  if (!x) throw Error("Unbekannter Fahrzeugtyp");
  return x;
};
const reports: Record<
  string,
  { name: string; org: Template["org"]; requirements: Skills }
> = {
  incoming: { name: "Ungeklärter Notruf", org: "Unbekannt", requirements: {} },
  "reported-fire": {
    name: "Brandverdacht gemeldet",
    org: "Feuerwehr",
    requirements: { fire: 1 },
  },
  "reported-technical": {
    name: "Technische Hilfe gemeldet",
    org: "Feuerwehr",
    requirements: { rescue: 1 },
  },
  "reported-medical": {
    name: "Medizinischer Notfall gemeldet",
    org: "Rettungsdienst",
    requirements: { medical: 1 },
  },
  "reported-police": {
    name: "Polizeiliche Hilfe gemeldet",
    org: "Polizei",
    requirements: { police: 1 },
  },
  "reported-water": {
    name: "Notlage am Wasser gemeldet",
    org: "Wasserrettung",
    requirements: { rescue: 1 },
  },
  "reported-other": {
    name: "Hilfegesuch gemeldet",
    org: "Unbekannt",
    requirements: {},
  },
};
export const mt = (id: string) => {
  if (Object.hasOwn(reports, id)) {
    const report = reports[id];
    return {
      id,
      ...report,
      description:
        id === "incoming"
          ? "Ort und Meldebild müssen erfragt werden."
          : "Vorläufige Einordnung aus den bekannten Beobachtungen. Weitere Lage durch Rückfragen und Erkundung klären.",
      seconds: 1,
      reward: 0,
      patients: 0,
      level: 1,
      water: false,
    } as Template;
  }
  const x =
    id === "bma"
      ? {
          ...missions[0],
          id: "bma",
          name: "Ausgelöste Brandmeldeanlage",
          description:
            "Automatische Brandmeldung. Ursache durch Erkundung feststellen.",
          reward: 0,
        }
      : missions.find((m) => m.id === id);
  if (!x) throw Error("Unbekannte Einsatzart");
  return x;
};
